version: '2'
services:
  db:
    image: postgres:9.5.3
    volumes:
       - ./pgdata:/pgdata
    environment:
       PGDATA: /pgdata
       POSTGRES_USER: listenbrainz
       POSTGRES_PASSWD: listenbrainz
       POSTGRES_DB: listenbrainz
  redis:
    image: redis:3.2.1
    volumes:
      - ./data/redis:/data
  web-test:
    build: .
    command: py.test
    volumes:
      - .:/code/listenbrainz-server
      - ./data/app:/data
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
